[build]
  publish = "docs/"
  command = "yarn && yarn docs:build"
  [build.environment]
    YARN_VERSION = "1.3.2"
    NODE_ENV = "production"

[context.production]
  PUBLIC_PATH = "/jekyll-algolia/"
